### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by caecos** [NikolajAndersson/RackPlugins#1]
compilation terminated.
make: *** [../../compile.mk:62: build/src/FuzzRack.cpp.o] Error 1

**Comment by NikolajAndersson** [comment]
Hello Caecos, 
You need to install Armadillo on your system to make the Fuzz work. Link: [https://solarianprogrammer.com/2017/03/24/getting-started-armadillo-cpp-linear-algebra-windows-mac-linux/](url) 
However, I will make a lot of changes (hopefully avoid using a matrix library) and update the graphics during the next couple of weeks.

Cheers

**Comment by caecos** [comment]
Thank's for the instruction...

**Comment by NikolajAndersson** [comment]
@caecos I will give an update in here when the plug-ins are in a better state. 
My plan is make a nice GUI and optimise the code.

**Comment by caecos** [comment]
Thx…fine and regards for the fast reply

Marc

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Nikolaj Andersson <notifications@github.com>
Envoyé : Tuesday, June 5, 2018 7:47:54 AM
À : NikolajAndersson/RackPlugins
Cc : caecos; Mention
Objet : Re: [NikolajAndersson/RackPlugins] Compiling error (#1)


@caecos<https://github.com/caecos> I will give an update in here when the plug-ins are in a better state.
My plan is make a nice GUI and optimise the code.
